module.exports = {
  bitter: [
    '<div class="col-sm-12">',
      '<div class="row">',
        '<div class="col-sm-3 imgContainer">',
          '<img src="<%=img%>">',
        '</div>',
        '<div class="col-sm-9 content">',
          '<span><%=date%></span>',
          '<p><%=content%></p>',
          '<section>',
            '<i class="fa fa-pencil-square-o"></i>',
            '<i class="fa fa-trash-o"></i>',
          '</section>',
        '</div>',
        '<form class="col-sm-12 editForm">',
        '</form>',
      '</div>',
    '</div>'
  ].join(''),
  addForm: [
    '<div class="addButton">',
      '<i class="fa fa-2x fa-plus-circle"></i>',
    '</div>',
    '<form class="addForm hide">',
      '<div class="form-group">',
        '<label for="img">Image URL</label>',
        '<input class="form-control" type="text" name="img" placeholder="Image URL">',
      '</div>',
      '<div class="form-group">',
        '<label for="content">Bitter Rant Here:</label>',
        '<textarea class="form-control" type="text" name="content" placeholder="Bitter Rant"></textarea>',
      '</div>',
      '<button class="btn btn-primary" name="submitAdd">Submit</button>',
    '</form>'
  ].join(''),
  editForm: [
    '<div class="form-group">',
      '<label for="img">Image URL</label>',
      '<input class="form-control" type="text" name="img" placeholder="Image URL" value="<%=img%>">',
    '</div>',
    '<div class="form-group">',
      '<label for="content">Bitter Rant Here:</label>',
      '<textarea class="form-control" type="text" name="content" placeholder="Bitter Rant"><%=content%></textarea>',
    '</div>',
    '<button class="btn btn-primary" name="submitEdit">Submit</button>',
  ].join('')
}
